### ISSUE TITLE
Create landing page content

### ISSUE THREAD

**Issue by NathanCastle** [ritstudentgovernment/evals#1]
Acceptance Criteria:
* [x] Explain the purpose of Course Evaluation System.
   * Provide students with a reliable source of information to make course enrollment decisions.
   * Better than alternative services that allow anybody to submit.
* [x] Explain the origin of the service.
  * Project is sponsored by Student Government.
  * Make it clear the project is open source.
* [x] Sell the service.
  * Our reviews are far more light-weight.
  * Offer gift cards to random, non-SG evaluators (permitting clearance from Dir. of Finance)
  * Show data in meaningful ways (e.g., "top professors" feature for a given course)

**Comment by petermikitsh** [comment]
A lot of this now explained on the about pages, so I'm going this issue.
